### ISSUE TITLE
installation instructions for biobambam outdated

### ISSUE THREAD

**Issue by williamrowell** [ExpressionAnalysis/STAR-SEQR#15]
```
PackageNotFoundError: Packages missing in current channels:

  - biobambam
```
Instead, try:
`conda install -c bioconda biobambam`

**Comment by williamrowell** [comment]
I spoke too soon.  You need `-c bioconda` for most if not all of these.

**Comment by jasper1918** [comment]
Great point! I've made it more clear for future users. Fill free to drop me a line sometime and let me know how starseqr performs for you.
